# ONE HOT ENCODING

In [1]:
import pandas as pd
import numpy as np

In [2]:
df=pd.read_csv(r"C:\Users\hp\Music\ml_classproject\all_csv_folder\one_hot_encoding_practice_100.csv")

In [3]:
df

    Age    City  Gender Department  Salary
0    21   Delhi    Male         IT   30000
1    28  Mumbai  Female    Finance   32700
2    35  Jaipur    Male      Sales   35400
3    42    Pune  Female         HR   38100
4    49   Delhi    Male         IT   40800
..  ...     ...     ...        ...     ...
95   26    Pune  Female         HR   36500
96   33   Delhi    Male         IT   39200
97   40  Mumbai  Female    Finance   41900
98   47  Jaipur    Male      Sales   44600
99   24    Pune  Female         HR   47300

[100 rows x 5 columns]

In [9]:
df["Gender"].value_counts()

Gender
Male      50
Female    50
Name: count, dtype: int64

In [12]:
# applying one hot encoding in city and department function
pd.get_dummies(df,columns=["City","Department"])

,Age,Gender,Salary,City_Delhi,City_Jaipur,City_Mumbai,City_Pune,Department_Finance,Department_HR,Department_IT,Department_Sales
0,21,Male,30000,True,False,False,False,False,False,True,False
1,28,Female,32700,False,False,True,False,True,False,False,False
2,35,Male,35400,False,True,False,False,False,False,False,True
3,42,Female,38100,False,False,False,True,False,True,False,False
4,49,Male,40800,True,False,False,False,False,False,True,False
...,...,...,...,...,...,...,...,...,...,...,...
95,26,Female,36500,False,False,False,True,False,True,False,False
96,33,Male,39200,True,False,False,False,False,False,True,False
97,40,Female,41900,False,False,True,False,True,False,False,False
98,47,Male,44600,False,True,False,False,False,False,False,True
99,24,Female,47300,False,False,False,True,False,True,False,False

In [13]:
# applying one hot encoding using the sklearn library
from sklearn.model_selection import train_test_split

In [14]:
X_train,x_test,Y_train,y_test =train_test_split(df.iloc[:,0:4],df.iloc[:,-1],test_size=0.2,random_state=42)

In [15]:
# one hot encoder
from sklearn.preprocessing import OneHotEncoder
ohe=OneHotEncoder()